/*
 * generated by Xtext
 */
package sle.gbt.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GBTSUiModule extends sle.gbt.xtext.ui.AbstractGBTSUiModule {
	public GBTSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
