/*
 * generated by Xtext
 */
package sle.fsml.run.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class RunUiModule extends sle.fsml.run.ui.AbstractRunUiModule {
	public RunUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
