/*
 * generated by Xtext
 */
package sle.fsml;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FSMLRuntimeModule extends sle.fsml.AbstractFSMLRuntimeModule {

}
