/*
 * generated by Xtext
 */
package eu.pasusu.megal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MegaLUiModule extends eu.pasusu.megal.ui.AbstractMegaLUiModule {
	public MegaLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
