/*
 * generated by Xtext
 */
package sle.fsml.input.validation

//import org.eclipse.xtext.validation.Check
/**
 * Input is not checked
 */
class InputValidator extends AbstractInputValidator
{
}
