/*
* generated by Xtext
*/
package sle.fsml.run.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class RunGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class RunfileElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Runfile");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cRunfileAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cRunsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRunsRunParserRuleCall_1_0 = (RuleCall)cRunsAssignment_1.eContents().get(0);
		
		//Runfile:
		//	{Runfile} runs+=Run+;
		public ParserRule getRule() { return rule; }

		//{Runfile} runs+=Run+
		public Group getGroup() { return cGroup; }

		//{Runfile}
		public Action getRunfileAction_0() { return cRunfileAction_0; }

		//runs+=Run+
		public Assignment getRunsAssignment_1() { return cRunsAssignment_1; }

		//Run
		public RuleCall getRunsRunParserRuleCall_1_0() { return cRunsRunParserRuleCall_1_0; }
	}

	public class RunElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Run");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRunKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMachineAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMachineSTRINGTerminalRuleCall_1_0 = (RuleCall)cMachineAssignment_1.eContents().get(0);
		private final Keyword cOnKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cInputAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cInputSTRINGTerminalRuleCall_3_0 = (RuleCall)cInputAssignment_3.eContents().get(0);
		private final Keyword cToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTargetAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTargetSTRINGTerminalRuleCall_5_0 = (RuleCall)cTargetAssignment_5.eContents().get(0);
		
		//Run:
		//	"run" machine=STRING "on" input=STRING "to" target=STRING;
		public ParserRule getRule() { return rule; }

		//"run" machine=STRING "on" input=STRING "to" target=STRING
		public Group getGroup() { return cGroup; }

		//"run"
		public Keyword getRunKeyword_0() { return cRunKeyword_0; }

		//machine=STRING
		public Assignment getMachineAssignment_1() { return cMachineAssignment_1; }

		//STRING
		public RuleCall getMachineSTRINGTerminalRuleCall_1_0() { return cMachineSTRINGTerminalRuleCall_1_0; }

		//"on"
		public Keyword getOnKeyword_2() { return cOnKeyword_2; }

		//input=STRING
		public Assignment getInputAssignment_3() { return cInputAssignment_3; }

		//STRING
		public RuleCall getInputSTRINGTerminalRuleCall_3_0() { return cInputSTRINGTerminalRuleCall_3_0; }

		//"to"
		public Keyword getToKeyword_4() { return cToKeyword_4; }

		//target=STRING
		public Assignment getTargetAssignment_5() { return cTargetAssignment_5; }

		//STRING
		public RuleCall getTargetSTRINGTerminalRuleCall_5_0() { return cTargetSTRINGTerminalRuleCall_5_0; }
	}
	
	
	private RunfileElements pRunfile;
	private RunElements pRun;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public RunGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("sle.fsml.run.Run".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Runfile:
	//	{Runfile} runs+=Run+;
	public RunfileElements getRunfileAccess() {
		return (pRunfile != null) ? pRunfile : (pRunfile = new RunfileElements());
	}
	
	public ParserRule getRunfileRule() {
		return getRunfileAccess().getRule();
	}

	//Run:
	//	"run" machine=STRING "on" input=STRING "to" target=STRING;
	public RunElements getRunAccess() {
		return (pRun != null) ? pRun : (pRun = new RunElements());
	}
	
	public ParserRule getRunRule() {
		return getRunAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
