/*
* generated by Xtext
*/
package sle.fsml.run.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sle.fsml.run.services.RunGrammarAccess;

public class RunParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private RunGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected sle.fsml.run.parser.antlr.internal.InternalRunParser createParser(XtextTokenStream stream) {
		return new sle.fsml.run.parser.antlr.internal.InternalRunParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Runfile";
	}
	
	public RunGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(RunGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
