/*
* generated by Xtext
*/
package sle.fsml.input.ui.quickfix

/**
 * There are no errors, so no quick-fixes required
 */
class InputQuickfixProvider extends org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider
{
}
