/*
* generated by Xtext
*/
package sle.fsml.input.ui.outline

/**
 * The default outline is not modified for the input
 */
class InputOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider
{
}
