/*
 * generated by Xtext
 */
package sle.fsml.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractFSMLValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(sle.fsml.fSML.FSMLPackage.eINSTANCE);
		return result;
	}
}
