/*
 * generated by Xtext
 */
package sle.gbt.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGBTSValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(sle.gbt.xtext.gBTS.GBTSPackage.eINSTANCE);
		return result;
	}
}
