/*
 * generated by Xtext
 */
package sle.fsml.input.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class InputUiModule extends sle.fsml.input.ui.AbstractInputUiModule {
	public InputUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
