/*
 * generated by Xtext
 */
package sle.fsml.run.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import sle.fsml.run.ui.internal.RunActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class RunExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return RunActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return RunActivator.getInstance().getInjector(RunActivator.SLE_FSML_RUN_RUN);
	}
	
}
