/**
 * generated by Xtext
 */
package sle.gbt.xtext.serializer;

import sle.gbt.xtext.serializer.AbstractGBTSSyntacticSequencer;

@SuppressWarnings("all")
public class GBTSSyntacticSequencer extends AbstractGBTSSyntacticSequencer {
}
