/**
 * generated by Xtext
 */
package sle.gbt.xtext.serializer;

import sle.gbt.xtext.serializer.AbstractGBTSSemanticSequencer;

@SuppressWarnings("all")
public class GBTSSemanticSequencer extends AbstractGBTSSemanticSequencer {
}
