/*
* generated by Xtext
*/
package sle.fsml.input;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class InputUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return sle.fsml.input.ui.internal.InputActivator.getInstance().getInjector("sle.fsml.input.Input");
	}
	
}
