/*
 * generated by Xtext
 */
package sle.fsml.run.validation

import sle.fsml.run.run.MachineLocation
import sle.fsml.run.run.RunPackage
import org.eclipse.xtext.validation.Check
import sle.fsml.run.run.InputLocation
import org.eclipse.emf.common.util.URI

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class RunValidator extends AbstractRunValidator
{
	@Check
	def checkMachineFileExists(MachineLocation l)
	{
		// Try to find resource in domain of the input object
		if(!l.eResource.resourceSet.URIConverter.exists(URI::createFileURI(l.location), null))
		{
			error('Cannot find file at ' + l.location, RunPackage.Literals.MACHINE_LOCATION__LOCATION);
		}
	}

	@Check
	def checkInputFileExists(InputLocation l)
	{
		// Try to find resource in domain of the input object
		if(!l.eResource.resourceSet.URIConverter.exists(URI::createFileURI(l.location), null))
		{
			error('Cannot find file at ' + l.location, RunPackage.Literals.INPUT_LOCATION__LOCATION);
		}
	}
}
