/*
* generated by Xtext
*/
package sle.gbt.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class GBTSGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Assignment cTstsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cTstsTestParserRuleCall_0 = (RuleCall)cTstsAssignment.eContents().get(0);
		
		//Model:
		//	tsts+=Test*;
		public ParserRule getRule() { return rule; }

		//tsts+=Test*
		public Assignment getTstsAssignment() { return cTstsAssignment; }

		//Test
		public RuleCall getTstsTestParserRuleCall_0() { return cTstsTestParserRuleCall_0; }
	}

	public class TestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Test");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTestKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cRefAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cRefGrammarCrossReference_3_0 = (CrossReference)cRefAssignment_3.eContents().get(0);
		private final RuleCall cRefGrammarGrammarIDParserRuleCall_3_0_1 = (RuleCall)cRefGrammarCrossReference_3_0.eContents().get(1);
		private final UnorderedGroup cUnorderedGroup_4 = (UnorderedGroup)cGroup.eContents().get(4);
		private final Group cGroup_4_0 = (Group)cUnorderedGroup_4.eContents().get(0);
		private final Assignment cHasLbrAssignment_4_0_0 = (Assignment)cGroup_4_0.eContents().get(0);
		private final Keyword cHasLbrLbrKeyword_4_0_0_0 = (Keyword)cHasLbrAssignment_4_0_0.eContents().get(0);
		private final Assignment cLbrAssignment_4_0_1 = (Assignment)cGroup_4_0.eContents().get(1);
		private final RuleCall cLbrINTTerminalRuleCall_4_0_1_0 = (RuleCall)cLbrAssignment_4_0_1.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cUnorderedGroup_4.eContents().get(1);
		private final Assignment cHasLbrInitialAssignment_4_1_0 = (Assignment)cGroup_4_1.eContents().get(0);
		private final Keyword cHasLbrInitialLbrKeyword_4_1_0_0 = (Keyword)cHasLbrInitialAssignment_4_1_0.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_4_1_1 = (Keyword)cGroup_4_1.eContents().get(1);
		private final Keyword cInitialKeyword_4_1_2 = (Keyword)cGroup_4_1.eContents().get(2);
		private final Assignment cLbrInitialAssignment_4_1_3 = (Assignment)cGroup_4_1.eContents().get(3);
		private final RuleCall cLbrInitialINTTerminalRuleCall_4_1_3_0 = (RuleCall)cLbrInitialAssignment_4_1_3.eContents().get(0);
		private final Group cGroup_4_2 = (Group)cUnorderedGroup_4.eContents().get(2);
		private final Assignment cHasStartruleAssignment_4_2_0 = (Assignment)cGroup_4_2.eContents().get(0);
		private final Keyword cHasStartruleStartKeyword_4_2_0_0 = (Keyword)cHasStartruleAssignment_4_2_0.eContents().get(0);
		private final Assignment cStartruleAssignment_4_2_1 = (Assignment)cGroup_4_2.eContents().get(1);
		private final CrossReference cStartruleAbstractRuleCrossReference_4_2_1_0 = (CrossReference)cStartruleAssignment_4_2_1.eContents().get(0);
		private final RuleCall cStartruleAbstractRuleIDTerminalRuleCall_4_2_1_0_1 = (RuleCall)cStartruleAbstractRuleCrossReference_4_2_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cMembersAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cMembersMemberParserRuleCall_6_0 = (RuleCall)cMembersAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Test:
		//	"test" name=ID ":=" ref=[xtext::Grammar|GrammarID] // Take override for length/breadth ratio
		//	((hasLbr?="lbr" lbr=INT)? // Take override for initial length/breadth value
		//	// Allow other startrule
		//	& (hasLbrInitial?="lbr" "-" "initial" lbrInitial=INT)? & (hasStartrule?="start" startrule=[xtext::AbstractRule])?) "{" // Fill with members
		//	members+=Member* "}";
		public ParserRule getRule() { return rule; }

		//"test" name=ID ":=" ref=[xtext::Grammar|GrammarID] // Take override for length/breadth ratio
		//((hasLbr?="lbr" lbr=INT)? // Take override for initial length/breadth value
		//// Allow other startrule
		//& (hasLbrInitial?="lbr" "-" "initial" lbrInitial=INT)? & (hasStartrule?="start" startrule=[xtext::AbstractRule])?) "{" // Fill with members
		//members+=Member* "}"
		public Group getGroup() { return cGroup; }

		//"test"
		public Keyword getTestKeyword_0() { return cTestKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//":="
		public Keyword getColonEqualsSignKeyword_2() { return cColonEqualsSignKeyword_2; }

		//ref=[xtext::Grammar|GrammarID]
		public Assignment getRefAssignment_3() { return cRefAssignment_3; }

		//[xtext::Grammar|GrammarID]
		public CrossReference getRefGrammarCrossReference_3_0() { return cRefGrammarCrossReference_3_0; }

		//GrammarID
		public RuleCall getRefGrammarGrammarIDParserRuleCall_3_0_1() { return cRefGrammarGrammarIDParserRuleCall_3_0_1; }

		//(hasLbr?="lbr" lbr=INT)? // Take override for initial length/breadth value
		//// Allow other startrule
		//& (hasLbrInitial?="lbr" "-" "initial" lbrInitial=INT)? & (hasStartrule?="start" startrule=[xtext::AbstractRule])?
		public UnorderedGroup getUnorderedGroup_4() { return cUnorderedGroup_4; }

		//(hasLbr?="lbr" lbr=INT)?
		public Group getGroup_4_0() { return cGroup_4_0; }

		//hasLbr?="lbr"
		public Assignment getHasLbrAssignment_4_0_0() { return cHasLbrAssignment_4_0_0; }

		//"lbr"
		public Keyword getHasLbrLbrKeyword_4_0_0_0() { return cHasLbrLbrKeyword_4_0_0_0; }

		//lbr=INT
		public Assignment getLbrAssignment_4_0_1() { return cLbrAssignment_4_0_1; }

		//INT
		public RuleCall getLbrINTTerminalRuleCall_4_0_1_0() { return cLbrINTTerminalRuleCall_4_0_1_0; }

		//(hasLbrInitial?="lbr" "-" "initial" lbrInitial=INT)?
		public Group getGroup_4_1() { return cGroup_4_1; }

		//hasLbrInitial?="lbr"
		public Assignment getHasLbrInitialAssignment_4_1_0() { return cHasLbrInitialAssignment_4_1_0; }

		//"lbr"
		public Keyword getHasLbrInitialLbrKeyword_4_1_0_0() { return cHasLbrInitialLbrKeyword_4_1_0_0; }

		//"-"
		public Keyword getHyphenMinusKeyword_4_1_1() { return cHyphenMinusKeyword_4_1_1; }

		//"initial"
		public Keyword getInitialKeyword_4_1_2() { return cInitialKeyword_4_1_2; }

		//lbrInitial=INT
		public Assignment getLbrInitialAssignment_4_1_3() { return cLbrInitialAssignment_4_1_3; }

		//INT
		public RuleCall getLbrInitialINTTerminalRuleCall_4_1_3_0() { return cLbrInitialINTTerminalRuleCall_4_1_3_0; }

		//(hasStartrule?="start" startrule=[xtext::AbstractRule])?
		public Group getGroup_4_2() { return cGroup_4_2; }

		//hasStartrule?="start"
		public Assignment getHasStartruleAssignment_4_2_0() { return cHasStartruleAssignment_4_2_0; }

		//"start"
		public Keyword getHasStartruleStartKeyword_4_2_0_0() { return cHasStartruleStartKeyword_4_2_0_0; }

		//startrule=[xtext::AbstractRule]
		public Assignment getStartruleAssignment_4_2_1() { return cStartruleAssignment_4_2_1; }

		//[xtext::AbstractRule]
		public CrossReference getStartruleAbstractRuleCrossReference_4_2_1_0() { return cStartruleAbstractRuleCrossReference_4_2_1_0; }

		//ID
		public RuleCall getStartruleAbstractRuleIDTerminalRuleCall_4_2_1_0_1() { return cStartruleAbstractRuleIDTerminalRuleCall_4_2_1_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }

		//// Fill with members
		//members+=Member*
		public Assignment getMembersAssignment_6() { return cMembersAssignment_6; }

		//Member
		public RuleCall getMembersMemberParserRuleCall_6_0() { return cMembersMemberParserRuleCall_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class MemberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Member");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cApplyParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSubParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cNewParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Member:
		//	Apply | Sub | New;
		public ParserRule getRule() { return rule; }

		//Apply | Sub | New
		public Alternatives getAlternatives() { return cAlternatives; }

		//Apply
		public RuleCall getApplyParserRuleCall_0() { return cApplyParserRuleCall_0; }

		//Sub
		public RuleCall getSubParserRuleCall_1() { return cSubParserRuleCall_1; }

		//New
		public RuleCall getNewParserRuleCall_2() { return cNewParserRuleCall_2; }
	}

	public class ApplyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Apply");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cApplyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMinOrItAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMinOrItINTTerminalRuleCall_1_0 = (RuleCall)cMinOrItAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Assignment cHasMaxAssignment_2_0 = (Assignment)cGroup_2.eContents().get(0);
		private final Keyword cHasMaxFullStopFullStopKeyword_2_0_0 = (Keyword)cHasMaxAssignment_2_0.eContents().get(0);
		private final Assignment cMaxAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cMaxINTTerminalRuleCall_2_1_0 = (RuleCall)cMaxAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Assignment cHasNumAssignment_3_0 = (Assignment)cGroup_3.eContents().get(0);
		private final Keyword cHasNumColonKeyword_3_0_0 = (Keyword)cHasNumAssignment_3_0.eContents().get(0);
		private final Assignment cNumAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cNumINTTerminalRuleCall_3_1_0 = (RuleCall)cNumAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Apply:
		//	"apply" minOrIt=INT (hasMax?=".." max=INT)? (hasNum?=":" num=INT)? ";";
		public ParserRule getRule() { return rule; }

		//"apply" minOrIt=INT (hasMax?=".." max=INT)? (hasNum?=":" num=INT)? ";"
		public Group getGroup() { return cGroup; }

		//"apply"
		public Keyword getApplyKeyword_0() { return cApplyKeyword_0; }

		//minOrIt=INT
		public Assignment getMinOrItAssignment_1() { return cMinOrItAssignment_1; }

		//INT
		public RuleCall getMinOrItINTTerminalRuleCall_1_0() { return cMinOrItINTTerminalRuleCall_1_0; }

		//(hasMax?=".." max=INT)?
		public Group getGroup_2() { return cGroup_2; }

		//hasMax?=".."
		public Assignment getHasMaxAssignment_2_0() { return cHasMaxAssignment_2_0; }

		//".."
		public Keyword getHasMaxFullStopFullStopKeyword_2_0_0() { return cHasMaxFullStopFullStopKeyword_2_0_0; }

		//max=INT
		public Assignment getMaxAssignment_2_1() { return cMaxAssignment_2_1; }

		//INT
		public RuleCall getMaxINTTerminalRuleCall_2_1_0() { return cMaxINTTerminalRuleCall_2_1_0; }

		//(hasNum?=":" num=INT)?
		public Group getGroup_3() { return cGroup_3; }

		//hasNum?=":"
		public Assignment getHasNumAssignment_3_0() { return cHasNumAssignment_3_0; }

		//":"
		public Keyword getHasNumColonKeyword_3_0_0() { return cHasNumColonKeyword_3_0_0; }

		//num=INT
		public Assignment getNumAssignment_3_1() { return cNumAssignment_3_1; }

		//INT
		public RuleCall getNumINTTerminalRuleCall_3_1_0() { return cNumINTTerminalRuleCall_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class SubElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Sub");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSubKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRuleAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cRuleAbstractRuleCrossReference_1_0 = (CrossReference)cRuleAssignment_1.eContents().get(0);
		private final RuleCall cRuleAbstractRuleIDTerminalRuleCall_1_0_1 = (RuleCall)cRuleAbstractRuleCrossReference_1_0.eContents().get(1);
		private final Keyword cColonEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSubstitutionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cSubstitutionSGParserRuleCall_3_0 = (RuleCall)cSubstitutionAssignment_3.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Sub:
		//	"sub" rule=[xtext::AbstractRule] ":=" substitution=SG ";";
		public ParserRule getRule() { return rule; }

		//"sub" rule=[xtext::AbstractRule] ":=" substitution=SG ";"
		public Group getGroup() { return cGroup; }

		//"sub"
		public Keyword getSubKeyword_0() { return cSubKeyword_0; }

		//rule=[xtext::AbstractRule]
		public Assignment getRuleAssignment_1() { return cRuleAssignment_1; }

		//[xtext::AbstractRule]
		public CrossReference getRuleAbstractRuleCrossReference_1_0() { return cRuleAbstractRuleCrossReference_1_0; }

		//ID
		public RuleCall getRuleAbstractRuleIDTerminalRuleCall_1_0_1() { return cRuleAbstractRuleIDTerminalRuleCall_1_0_1; }

		//":="
		public Keyword getColonEqualsSignKeyword_2() { return cColonEqualsSignKeyword_2; }

		//substitution=SG
		public Assignment getSubstitutionAssignment_3() { return cSubstitutionAssignment_3; }

		//SG
		public RuleCall getSubstitutionSGParserRuleCall_3_0() { return cSubstitutionSGParserRuleCall_3_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class NewElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "New");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNewKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTermAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final Keyword cTermTerminalKeyword_1_0 = (Keyword)cTermAssignment_1.eContents().get(0);
		private final Assignment cRuleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRuleIDTerminalRuleCall_2_0 = (RuleCall)cRuleAssignment_2.eContents().get(0);
		private final Keyword cColonEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cDefinitionAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cDefinitionSGParserRuleCall_4_0 = (RuleCall)cDefinitionAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//New:
		//	"new" term?="terminal"? rule=ID ":=" definition=SG ";";
		public ParserRule getRule() { return rule; }

		//"new" term?="terminal"? rule=ID ":=" definition=SG ";"
		public Group getGroup() { return cGroup; }

		//"new"
		public Keyword getNewKeyword_0() { return cNewKeyword_0; }

		//term?="terminal"?
		public Assignment getTermAssignment_1() { return cTermAssignment_1; }

		//"terminal"
		public Keyword getTermTerminalKeyword_1_0() { return cTermTerminalKeyword_1_0; }

		//rule=ID
		public Assignment getRuleAssignment_2() { return cRuleAssignment_2; }

		//ID
		public RuleCall getRuleIDTerminalRuleCall_2_0() { return cRuleIDTerminalRuleCall_2_0; }

		//":="
		public Keyword getColonEqualsSignKeyword_3() { return cColonEqualsSignKeyword_3; }

		//definition=SG
		public Assignment getDefinitionAssignment_4() { return cDefinitionAssignment_4; }

		//SG
		public RuleCall getDefinitionSGParserRuleCall_4_0() { return cDefinitionSGParserRuleCall_4_0; }

		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}

	public class SGElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SG");
		private final RuleCall cAlternativeParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//SG returns sg::SG:
		//	Alternative;
		public ParserRule getRule() { return rule; }

		//Alternative
		public RuleCall getAlternativeParserRuleCall() { return cAlternativeParserRuleCall; }
	}

	public class AlternativeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Alternative");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cSequenceParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAlternativeLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cVerticalLineKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAlternativeParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Alternative returns sg::SG:
		//	Sequence ({sg::Alternative.left=current} "|" right=Alternative)?;
		public ParserRule getRule() { return rule; }

		//Sequence ({sg::Alternative.left=current} "|" right=Alternative)?
		public Group getGroup() { return cGroup; }

		//Sequence
		public RuleCall getSequenceParserRuleCall_0() { return cSequenceParserRuleCall_0; }

		//({sg::Alternative.left=current} "|" right=Alternative)?
		public Group getGroup_1() { return cGroup_1; }

		//{sg::Alternative.left=current}
		public Action getAlternativeLeftAction_1_0() { return cAlternativeLeftAction_1_0; }

		//"|"
		public Keyword getVerticalLineKeyword_1_1() { return cVerticalLineKeyword_1_1; }

		//right=Alternative
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//Alternative
		public RuleCall getRightAlternativeParserRuleCall_1_2_0() { return cRightAlternativeParserRuleCall_1_2_0; }
	}

	public class SequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Sequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cCardinalityParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cSequenceLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightSequenceParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Sequence returns sg::SG:
		//	Cardinality ({sg::Sequence.left=current} right=Sequence)?;
		public ParserRule getRule() { return rule; }

		//Cardinality ({sg::Sequence.left=current} right=Sequence)?
		public Group getGroup() { return cGroup; }

		//Cardinality
		public RuleCall getCardinalityParserRuleCall_0() { return cCardinalityParserRuleCall_0; }

		//({sg::Sequence.left=current} right=Sequence)?
		public Group getGroup_1() { return cGroup_1; }

		//{sg::Sequence.left=current}
		public Action getSequenceLeftAction_1_0() { return cSequenceLeftAction_1_0; }

		//right=Sequence
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }

		//Sequence
		public RuleCall getRightSequenceParserRuleCall_1_1_0() { return cRightSequenceParserRuleCall_1_1_0; }
	}

	public class CardinalityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Cardinality");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cOperatedParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Action cOptionalOfAction_1_0_0 = (Action)cGroup_1_0.eContents().get(0);
		private final Keyword cQuestionMarkKeyword_1_0_1 = (Keyword)cGroup_1_0.eContents().get(1);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Action cStarOfAction_1_1_0 = (Action)cGroup_1_1.eContents().get(0);
		private final Keyword cAsteriskKeyword_1_1_1 = (Keyword)cGroup_1_1.eContents().get(1);
		private final Group cGroup_1_2 = (Group)cAlternatives_1.eContents().get(2);
		private final Action cPlusOfAction_1_2_0 = (Action)cGroup_1_2.eContents().get(0);
		private final Keyword cPlusSignKeyword_1_2_1 = (Keyword)cGroup_1_2.eContents().get(1);
		
		//Cardinality returns sg::SG:
		//	Operated ({sg::Optional.of=current} "?" | {sg::Star.of=current} "*" | {sg::Plus.of=current} "+")?;
		public ParserRule getRule() { return rule; }

		//Operated ({sg::Optional.of=current} "?" | {sg::Star.of=current} "*" | {sg::Plus.of=current} "+")?
		public Group getGroup() { return cGroup; }

		//Operated
		public RuleCall getOperatedParserRuleCall_0() { return cOperatedParserRuleCall_0; }

		//({sg::Optional.of=current} "?" | {sg::Star.of=current} "*" | {sg::Plus.of=current} "+")?
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//{sg::Optional.of=current} "?"
		public Group getGroup_1_0() { return cGroup_1_0; }

		//{sg::Optional.of=current}
		public Action getOptionalOfAction_1_0_0() { return cOptionalOfAction_1_0_0; }

		//"?"
		public Keyword getQuestionMarkKeyword_1_0_1() { return cQuestionMarkKeyword_1_0_1; }

		//{sg::Star.of=current} "*"
		public Group getGroup_1_1() { return cGroup_1_1; }

		//{sg::Star.of=current}
		public Action getStarOfAction_1_1_0() { return cStarOfAction_1_1_0; }

		//"*"
		public Keyword getAsteriskKeyword_1_1_1() { return cAsteriskKeyword_1_1_1; }

		//{sg::Plus.of=current} "+"
		public Group getGroup_1_2() { return cGroup_1_2; }

		//{sg::Plus.of=current}
		public Action getPlusOfAction_1_2_0() { return cPlusOfAction_1_2_0; }

		//"+"
		public Keyword getPlusSignKeyword_1_2_1() { return cPlusSignKeyword_1_2_1; }
	}

	public class OperatedElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Operated");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusGreaterThanSignKeyword_0_0 = (Keyword)cGroup_0.eContents().get(0);
		private final Action cUntilAction_0_1 = (Action)cGroup_0.eContents().get(1);
		private final Assignment cOfAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cOfOperatedParserRuleCall_0_2_0 = (RuleCall)cOfAssignment_0_2.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cExclamationMarkKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Action cNegationAction_1_1 = (Action)cGroup_1.eContents().get(1);
		private final Assignment cOfAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cOfOperatedParserRuleCall_1_2_0 = (RuleCall)cOfAssignment_1_2.eContents().get(0);
		private final RuleCall cTerminalParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Operated returns sg::SG:
		//	"->" {sg::Until} of=Operated | "!" {sg::Negation} of=Operated | Terminal;
		public ParserRule getRule() { return rule; }

		//"->" {sg::Until} of=Operated | "!" {sg::Negation} of=Operated | Terminal
		public Alternatives getAlternatives() { return cAlternatives; }

		//"->" {sg::Until} of=Operated
		public Group getGroup_0() { return cGroup_0; }

		//"->"
		public Keyword getHyphenMinusGreaterThanSignKeyword_0_0() { return cHyphenMinusGreaterThanSignKeyword_0_0; }

		//{sg::Until}
		public Action getUntilAction_0_1() { return cUntilAction_0_1; }

		//of=Operated
		public Assignment getOfAssignment_0_2() { return cOfAssignment_0_2; }

		//Operated
		public RuleCall getOfOperatedParserRuleCall_0_2_0() { return cOfOperatedParserRuleCall_0_2_0; }

		//"!" {sg::Negation} of=Operated
		public Group getGroup_1() { return cGroup_1; }

		//"!"
		public Keyword getExclamationMarkKeyword_1_0() { return cExclamationMarkKeyword_1_0; }

		//{sg::Negation}
		public Action getNegationAction_1_1() { return cNegationAction_1_1; }

		//of=Operated
		public Assignment getOfAssignment_1_2() { return cOfAssignment_1_2; }

		//Operated
		public RuleCall getOfOperatedParserRuleCall_1_2_0() { return cOfOperatedParserRuleCall_1_2_0; }

		//Terminal
		public RuleCall getTerminalParserRuleCall_2() { return cTerminalParserRuleCall_2; }
	}

	public class TerminalElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Terminal");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cRangeAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cMinAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cMinSTRINGTerminalRuleCall_0_1_0 = (RuleCall)cMinAssignment_0_1.eContents().get(0);
		private final Keyword cFullStopFullStopKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Assignment cMaxAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cMaxSTRINGTerminalRuleCall_0_3_0 = (RuleCall)cMaxAssignment_0_3.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cSingleAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cTokenAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cTokenSTRINGTerminalRuleCall_1_1_0 = (RuleCall)cTokenAssignment_1_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cReferenceAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final Assignment cToAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cToIDTerminalRuleCall_2_1_0 = (RuleCall)cToAssignment_2_1.eContents().get(0);
		private final RuleCall cParenthesizedElementParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Terminal returns sg::SG:
		//	{sg::Range} min=STRING ".." max=STRING | {sg::Single} token=STRING | {sg::Reference} to=ID | ParenthesizedElement;
		public ParserRule getRule() { return rule; }

		//{sg::Range} min=STRING ".." max=STRING | {sg::Single} token=STRING | {sg::Reference} to=ID | ParenthesizedElement
		public Alternatives getAlternatives() { return cAlternatives; }

		//{sg::Range} min=STRING ".." max=STRING
		public Group getGroup_0() { return cGroup_0; }

		//{sg::Range}
		public Action getRangeAction_0_0() { return cRangeAction_0_0; }

		//min=STRING
		public Assignment getMinAssignment_0_1() { return cMinAssignment_0_1; }

		//STRING
		public RuleCall getMinSTRINGTerminalRuleCall_0_1_0() { return cMinSTRINGTerminalRuleCall_0_1_0; }

		//".."
		public Keyword getFullStopFullStopKeyword_0_2() { return cFullStopFullStopKeyword_0_2; }

		//max=STRING
		public Assignment getMaxAssignment_0_3() { return cMaxAssignment_0_3; }

		//STRING
		public RuleCall getMaxSTRINGTerminalRuleCall_0_3_0() { return cMaxSTRINGTerminalRuleCall_0_3_0; }

		//{sg::Single} token=STRING
		public Group getGroup_1() { return cGroup_1; }

		//{sg::Single}
		public Action getSingleAction_1_0() { return cSingleAction_1_0; }

		//token=STRING
		public Assignment getTokenAssignment_1_1() { return cTokenAssignment_1_1; }

		//STRING
		public RuleCall getTokenSTRINGTerminalRuleCall_1_1_0() { return cTokenSTRINGTerminalRuleCall_1_1_0; }

		//{sg::Reference} to=ID
		public Group getGroup_2() { return cGroup_2; }

		//{sg::Reference}
		public Action getReferenceAction_2_0() { return cReferenceAction_2_0; }

		//to=ID
		public Assignment getToAssignment_2_1() { return cToAssignment_2_1; }

		//ID
		public RuleCall getToIDTerminalRuleCall_2_1_0() { return cToIDTerminalRuleCall_2_1_0; }

		//ParenthesizedElement
		public RuleCall getParenthesizedElementParserRuleCall_3() { return cParenthesizedElementParserRuleCall_3; }
	}

	public class ParenthesizedElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ParenthesizedElement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cAlternativeParserRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ParenthesizedElement returns sg::SG:
		//	"(" Alternative ")";
		public ParserRule getRule() { return rule; }

		//"(" Alternative ")"
		public Group getGroup() { return cGroup; }

		//"("
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }

		//Alternative
		public RuleCall getAlternativeParserRuleCall_1() { return cAlternativeParserRuleCall_1; }

		//")"
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}

	public class GrammarIDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GrammarID");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//GrammarID returns ecore::EString:
		//	ID ("." ID)*;
		public ParserRule getRule() { return rule; }

		//ID ("." ID)*
		public Group getGroup() { return cGroup; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//("." ID)*
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1_1() { return cIDTerminalRuleCall_1_1; }
	}
	
	
	private ModelElements pModel;
	private TestElements pTest;
	private MemberElements pMember;
	private ApplyElements pApply;
	private SubElements pSub;
	private NewElements pNew;
	private SGElements pSG;
	private AlternativeElements pAlternative;
	private SequenceElements pSequence;
	private CardinalityElements pCardinality;
	private OperatedElements pOperated;
	private TerminalElements pTerminal;
	private ParenthesizedElementElements pParenthesizedElement;
	private GrammarIDElements pGrammarID;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public GBTSGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("sle.gbt.xtext.GBTS".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	tsts+=Test*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Test:
	//	"test" name=ID ":=" ref=[xtext::Grammar|GrammarID] // Take override for length/breadth ratio
	//	((hasLbr?="lbr" lbr=INT)? // Take override for initial length/breadth value
	//	// Allow other startrule
	//	& (hasLbrInitial?="lbr" "-" "initial" lbrInitial=INT)? & (hasStartrule?="start" startrule=[xtext::AbstractRule])?) "{" // Fill with members
	//	members+=Member* "}";
	public TestElements getTestAccess() {
		return (pTest != null) ? pTest : (pTest = new TestElements());
	}
	
	public ParserRule getTestRule() {
		return getTestAccess().getRule();
	}

	//Member:
	//	Apply | Sub | New;
	public MemberElements getMemberAccess() {
		return (pMember != null) ? pMember : (pMember = new MemberElements());
	}
	
	public ParserRule getMemberRule() {
		return getMemberAccess().getRule();
	}

	//Apply:
	//	"apply" minOrIt=INT (hasMax?=".." max=INT)? (hasNum?=":" num=INT)? ";";
	public ApplyElements getApplyAccess() {
		return (pApply != null) ? pApply : (pApply = new ApplyElements());
	}
	
	public ParserRule getApplyRule() {
		return getApplyAccess().getRule();
	}

	//Sub:
	//	"sub" rule=[xtext::AbstractRule] ":=" substitution=SG ";";
	public SubElements getSubAccess() {
		return (pSub != null) ? pSub : (pSub = new SubElements());
	}
	
	public ParserRule getSubRule() {
		return getSubAccess().getRule();
	}

	//New:
	//	"new" term?="terminal"? rule=ID ":=" definition=SG ";";
	public NewElements getNewAccess() {
		return (pNew != null) ? pNew : (pNew = new NewElements());
	}
	
	public ParserRule getNewRule() {
		return getNewAccess().getRule();
	}

	//SG returns sg::SG:
	//	Alternative;
	public SGElements getSGAccess() {
		return (pSG != null) ? pSG : (pSG = new SGElements());
	}
	
	public ParserRule getSGRule() {
		return getSGAccess().getRule();
	}

	//Alternative returns sg::SG:
	//	Sequence ({sg::Alternative.left=current} "|" right=Alternative)?;
	public AlternativeElements getAlternativeAccess() {
		return (pAlternative != null) ? pAlternative : (pAlternative = new AlternativeElements());
	}
	
	public ParserRule getAlternativeRule() {
		return getAlternativeAccess().getRule();
	}

	//Sequence returns sg::SG:
	//	Cardinality ({sg::Sequence.left=current} right=Sequence)?;
	public SequenceElements getSequenceAccess() {
		return (pSequence != null) ? pSequence : (pSequence = new SequenceElements());
	}
	
	public ParserRule getSequenceRule() {
		return getSequenceAccess().getRule();
	}

	//Cardinality returns sg::SG:
	//	Operated ({sg::Optional.of=current} "?" | {sg::Star.of=current} "*" | {sg::Plus.of=current} "+")?;
	public CardinalityElements getCardinalityAccess() {
		return (pCardinality != null) ? pCardinality : (pCardinality = new CardinalityElements());
	}
	
	public ParserRule getCardinalityRule() {
		return getCardinalityAccess().getRule();
	}

	//Operated returns sg::SG:
	//	"->" {sg::Until} of=Operated | "!" {sg::Negation} of=Operated | Terminal;
	public OperatedElements getOperatedAccess() {
		return (pOperated != null) ? pOperated : (pOperated = new OperatedElements());
	}
	
	public ParserRule getOperatedRule() {
		return getOperatedAccess().getRule();
	}

	//Terminal returns sg::SG:
	//	{sg::Range} min=STRING ".." max=STRING | {sg::Single} token=STRING | {sg::Reference} to=ID | ParenthesizedElement;
	public TerminalElements getTerminalAccess() {
		return (pTerminal != null) ? pTerminal : (pTerminal = new TerminalElements());
	}
	
	public ParserRule getTerminalRule() {
		return getTerminalAccess().getRule();
	}

	//ParenthesizedElement returns sg::SG:
	//	"(" Alternative ")";
	public ParenthesizedElementElements getParenthesizedElementAccess() {
		return (pParenthesizedElement != null) ? pParenthesizedElement : (pParenthesizedElement = new ParenthesizedElementElements());
	}
	
	public ParserRule getParenthesizedElementRule() {
		return getParenthesizedElementAccess().getRule();
	}

	//GrammarID returns ecore::EString:
	//	ID ("." ID)*;
	public GrammarIDElements getGrammarIDAccess() {
		return (pGrammarID != null) ? pGrammarID : (pGrammarID = new GrammarIDElements());
	}
	
	public ParserRule getGrammarIDRule() {
		return getGrammarIDAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
