/*
 * generated by Xtext
 */
package sle.fsml.input.ui.contentassist

import sle.fsml.input.ui.contentassist.AbstractInputProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class InputProposalProvider extends AbstractInputProposalProvider {
}
