/*
 * generated by Xtext
 */
package sle.gbt.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import sle.gbt.xtext.ui.internal.GBTSActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GBTSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GBTSActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GBTSActivator.getInstance().getInjector(GBTSActivator.SLE_GBT_XTEXT_GBTS);
	}
	
}
