/*
 * generated by Xtext
 */
package sle.fsml.input.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import sle.fsml.input.ui.internal.InputActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class InputExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return InputActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return InputActivator.getInstance().getInjector(InputActivator.SLE_FSML_INPUT_INPUT);
	}
	
}
