/*
 * generated by Xtext
 */
package sle.fsml.ui.contentassist

import sle.fsml.ui.contentassist.AbstractFSMLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class FSMLProposalProvider extends AbstractFSMLProposalProvider {
}
