/*
 * generated by Xtext
 */
package sle.fsml.ui.contentassist

import sle.fsml.ui.contentassist.AbstractFSMLProposalProvider

/**
 * The FSM editor does not provide proposals
 */
class FSMLProposalProvider extends AbstractFSMLProposalProvider
{
}
