/**
 * generated by Xtext
 */
package sle.gbt.xtext.validation;

import sle.gbt.xtext.validation.AbstractGBTSValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class GBTSValidator extends AbstractGBTSValidator {
}
