/*
 * generated by Xtext
 */
package sle.fsml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FSMLUiModule extends sle.fsml.ui.AbstractFSMLUiModule {
	public FSMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
