/*
 * generated by Xtext
 */
package eu.pasusu.megal.ui.contentassist

import eu.pasusu.megal.ui.contentassist.AbstractMegaLProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class MegaLProposalProvider extends AbstractMegaLProposalProvider {
}
