/*
 * generated by Xtext
 */
package sle.fsml.run.ui.contentassist

import sle.fsml.run.ui.contentassist.AbstractRunProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class RunProposalProvider extends AbstractRunProposalProvider {
}
