/*
 * generated by Xtext
 */
package eu.pasusu.megal;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MegaLRuntimeModule extends eu.pasusu.megal.AbstractMegaLRuntimeModule {

}
