/*
 * generated by Xtext
 */
package sle.gbt.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GBTSRuntimeModule extends sle.gbt.xtext.AbstractGBTSRuntimeModule {

}
