/*
* generated by Xtext
*/
package sle.fsml.input.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sle.fsml.input.services.InputGrammarAccess;

public class InputParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private InputGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_CM", "RULE_WS");
	}
	
	@Override
	protected sle.fsml.input.parser.antlr.internal.InternalInputParser createParser(XtextTokenStream stream) {
		return new sle.fsml.input.parser.antlr.internal.InternalInputParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Input";
	}
	
	public InputGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(InputGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
