/*
 * generated by Xtext
 */
package sle.fsml.run;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RunRuntimeModule extends sle.fsml.run.AbstractRunRuntimeModule {

}
