/*
* generated by Xtext
*/
package sle.fsml.run;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class RunStandaloneSetup extends RunStandaloneSetupGenerated{

	public static void doSetup() {
		new RunStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

