/*
* generated by Xtext
*/
package sle.fsml.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import sle.fsml.services.FSMLGrammarAccess;

public class FSMLParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private FSMLGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected sle.fsml.parser.antlr.internal.InternalFSMLParser createParser(XtextTokenStream stream) {
		return new sle.fsml.parser.antlr.internal.InternalFSMLParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "FSM";
	}
	
	public FSMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(FSMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
