/*
 * generated by Xtext
 */
package sle.fsml.input.scoping

/**
 * Input has no scopes as it has no cross-references
 */
class InputScopeProvider extends org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider
{
}
