grammar sle.fsml.input.Input hidden(CM, WS)

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
generate input "http://www.fsml.sle/input/Input"

Input:
	{Inputfile} (name=ID ':')? '[' (inputs+=InputEntry (',' inputs+=InputEntry)*)? ']' '.';

InputEntry:
	value=ID;

terminal ID:
	('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;

terminal CM:
	'%' !('\n' | '\r')* ('\r'? '\n')?;

terminal WS:
	(' ' | '\t' | '\r' | '\n')+;