/*
 * generated by Xtext
 */
package sle.fsml.input;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class InputRuntimeModule extends sle.fsml.input.AbstractInputRuntimeModule {

}
