/*
 * generated by Xtext
 */
package sle.fsml.input.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractInputValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(sle.fsml.input.input.InputPackage.eINSTANCE);
		return result;
	}
}
