/*
 * generated by Xtext
 */
package eu.pasusu.megal.validation

import org.eclipse.xtext.validation.Check
import eu.pasusu.megal.megaL.EntityTypeDeclaration
import eu.pasusu.megal.megaL.MegaLPackage

/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class MegaLValidator extends AbstractMegaLValidator {

  public static val INVALID_NAME = 'invalidName'

	@Check
	def checkValidTypeName(EntityTypeDeclaration entityTypeDeclaration) {
		if (!entityTypeDeclaration.name.endsWith("42")) {
			warning('Name should end with a 42', 
					MegaLPackage.Literals.ENTITY_TYPE_DECLARATION__NAME,
					INVALID_NAME)
		}
	}
}
