/*
* generated by Xtext
*/
package sle.fsml.input.ui.labeling

/**
 * Not required for the input
 */
class InputDescriptionLabelProvider extends org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider
{
}
