/*
* generated by Xtext
*/
package sle.gbt.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GBTSUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return sle.gbt.xtext.ui.internal.GBTSActivator.getInstance().getInjector("sle.gbt.xtext.GBTS");
	}
	
}
