/*
 * generated by Xtext
 */
package sle.gbt.xtext.ui.contentassist

import sle.gbt.xtext.ui.contentassist.AbstractGBTSProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GBTSProposalProvider extends AbstractGBTSProposalProvider {
}
